# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "shoplight"
client_id = "2b13a35f7da32d0b0846c90cb22b5694"
application_url = "http://localhost:3000"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "https://example.com/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://example.com/auth/callback",
  "https://example.com/auth/shopify/callback",
  "https://example.com/api/auth/callback"
]

[pos]
embedded = false
